use car_sales_management;
-- Find the total number of cars sold by each dealer
SELECT d.name AS dealer_name, COUNT(s.sale_id) AS total_sales
FROM Dealers d
JOIN Sales s ON d.dealer_id = s.dealer_id
GROUP BY d.name;

-- Find the total sales amount by each dealer
SELECT d.name AS dealer_name, SUM(s.sale_price) AS total_sales_amount
FROM Dealers d
JOIN Sales s ON d.dealer_id = s.dealer_id
GROUP BY d.name;

-- Find the number of cars sold in each city
SELECT c.city, COUNT(s.sale_id) AS cars_sold
FROM Customers c
JOIN Sales s ON c.customer_id = s.customer_id
GROUP BY c.city;

-- Find the most popular car model (by number of sales)
SELECT car.model, COUNT(s.sale_id) AS sales_count
FROM Cars car
JOIN Sales s ON car.car_id = s.car_id
GROUP BY car.model
ORDER BY sales_count DESC
LIMIT 1;

-- Calculate the average sale price of each car model
SELECT car.model, AVG(s.sale_price) AS average_price
FROM Cars car
JOIN Sales s ON car.car_id = s.car_id
GROUP BY car.model;

-- Find the total revenue generated by each car model
SELECT car.model, SUM(s.sale_price) AS total_revenue
FROM Cars car
JOIN Sales s ON car.car_id = s.car_id
GROUP BY car.model;

-- Find the customers who bought more than one car
SELECT c.name, COUNT(s.sale_id) AS cars_bought
FROM Customers c
JOIN Sales s ON c.customer_id = s.customer_id
GROUP BY c.name
HAVING cars_bought > 1;

-- Find the car models that have received the most services
SELECT car.model, COUNT(sr.service_id) AS service_count
FROM Cars car
JOIN Services sr ON car.car_id = sr.car_id
GROUP BY car.model
ORDER BY service_count DESC;

-- Find the most common type of service performed
SELECT sr.description, COUNT(sr.service_id) AS service_count
FROM Services sr
GROUP BY sr.description
ORDER BY service_count DESC
LIMIT 1;

-- Calculate the total cost of services performed for each car model
SELECT car.model, SUM(sr.cost) AS total_service_cost
FROM Cars car
JOIN Services sr ON car.car_id = sr.car_id
GROUP BY car.model;

-- Find all sales that occurred in 2023
SELECT s.sale_id, car.model, cus.name AS customer_name, dea.name AS dealer_name, s.sale_date, s.sale_price
FROM Sales s
JOIN Cars car ON s.car_id = car.car_id
JOIN Customers cus ON s.customer_id = cus.customer_id
JOIN Dealers dea ON s.dealer_id = dea.dealer_id
WHERE YEAR(s.sale_date) = 2023;

-- Find the dealers who sold more than $100,000 in total sales
SELECT d.name AS dealer_name, SUM(s.sale_price) AS total_sales
FROM Dealers d
JOIN Sales s ON d.dealer_id = s.dealer_id
GROUP BY d.name
HAVING total_sales > 100000;

-- Find the average service cost per car model
SELECT car.model, AVG(sr.cost) AS average_service_cost
FROM Cars car
JOIN Services sr ON car.car_id = sr.car_id
GROUP BY car.model;

-- Find the cars sold by a specific dealer (e.g., 'Auto World')
SELECT car.model, car.brand, car.year, s.sale_price
FROM Cars car
JOIN Sales s ON car.car_id = s.car_id
JOIN Dealers d ON s.dealer_id = d.dealer_id
WHERE d.name = 'Auto World';

-- Find the customers who have not made any purchases
SELECT cus.name
FROM Customers cus
LEFT JOIN Sales s ON cus.customer_id = s.customer_id
WHERE s.customer_id IS NULL;
